[package]
name = "lambdax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_http = "0.7.3"
serde = "1.0.152"
tokio = "1.24.2"
